Simplify implementation for building Docker image

diff --git a/templates/opt/atlassian/confluence/bin/setenv.sh.j2 b/templates/opt/atlassian/confluence/bin/setenv.sh.j2
--- a/templates/opt/atlassian/confluence/bin/setenv.sh.j2
+++ b/templates/opt/atlassian/confluence/bin/setenv.sh.j2
@@ -16,16 +16,16 @@ export CATALINA_PID
 
 PRGDIR=`dirname "$0"`
 if [ -z "$CATALINA_BASE" ]; then
-    if [ -z "$CATALINA_HOME" ]; then
-        LOGBASE=$PRGDIR
-        LOGTAIL=..
-    else
-        LOGBASE=$CATALINA_HOME
-        LOGTAIL=.
-    fi
-else
-    LOGBASE=$CATALINA_BASE
+  if [ -z "$CATALINA_HOME" ]; then
+    LOGBASE=$PRGDIR
+    LOGTAIL=..
+  else
+    LOGBASE=$CATALINA_HOME
     LOGTAIL=.
+  fi
+else
+  LOGBASE=$CATALINA_BASE
+  LOGTAIL=.
 fi
 
 PUSHED_DIR=`pwd`
@@ -39,24 +39,24 @@ echo "Server startup logs are located in $LOGBASEABS/logs/catalina.out"
 # IMPORTANT NOTE: Only set JAVA_HOME or JRE_HOME above this line
 # Get standard Java environment variables
 if $os400; then
-    # -r will Only work on the os400 if the files are:
-    # 1. owned by the user
-    # 2. owned by the PRIMARY group of the user
-    # this will not work if the user belongs in secondary groups
-    . "$CATALINA_HOME"/bin/setjre.sh
+  # -r will Only work on the os400 if the files are:
+  # 1. owned by the user
+  # 2. owned by the PRIMARY group of the user
+  # this will not work if the user belongs in secondary groups
+  . "$CATALINA_HOME"/bin/setjre.sh
 else
-    if [ -r "$CATALINA_HOME"/bin/setjre.sh ]; then
-        . "$CATALINA_HOME"/bin/setjre.sh
-    else
-        echo "Cannot find $CATALINA_HOME/bin/setjre.sh"
-        echo "This file is needed to run this program"
-        exit 1
-    fi
+  if [ -r "$CATALINA_HOME"/bin/setjre.sh ]; then
+    . "$CATALINA_HOME"/bin/setjre.sh
+  else
+    echo "Cannot find $CATALINA_HOME/bin/setjre.sh"
+    echo "This file is needed to run this program"
+    exit 1
+  fi
 fi
 
 echo "---------------------------------------------------------------------------"
 echo "Using Java: $JRE_HOME/bin/java"
-CONFLUENCE_CONTEXT_PATH=`$JRE_HOME/bin/java -jar $CATALINA_HOME/bin/confluence-context-path-extractor.jar $CATALINA_HOME`
+CONFLUENCE_CONTEXT_PATH=${CATALINA_CONTEXT_PATH:-"{{ confluence_catalina_context_path }}"}
 export CONFLUENCE_CONTEXT_PATH
 $JRE_HOME/bin/java -jar $CATALINA_HOME/bin/synchrony-proxy-watchdog.jar $CATALINA_HOME
 echo "---------------------------------------------------------------------------"
@@ -67,12 +67,20 @@ CATALINA_OPTS="-XX:-PrintGCDetails -XX:+PrintGCDateStamps -XX:-PrintTenuringDist
 CATALINA_OPTS="-Xloggc:$LOGBASEABS/logs/gc-`date +%F_%H-%M-%S`.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=2M ${CATALINA_OPTS}"
 CATALINA_OPTS="-XX:G1ReservePercent=20 ${CATALINA_OPTS}"
 CATALINA_OPTS="-Djava.awt.headless=true ${CATALINA_OPTS}"
-CATALINA_OPTS="{{ confluence_jvm_support_recommended_args }} ${CATALINA_OPTS}"
-CATALINA_OPTS="-Xms{{ confluence_jvm_minimum_memory }} -Xmx{{ confluence_jvm_maximum_memory }} -XX:+UseG1GC ${CATALINA_OPTS}"
+CATALINA_OPTS="-D${JVM_SUPPORT_RECOMMENDED_ARGS:-"{{ confluence_jvm_support_recommended_args }}"} ${CATALINA_OPTS}"
+CATALINA_OPTS="-Xms${JVM_MINIMUM_MEMORY:-"{{ confluence_jvm_minimum_memory }}"} -Xmx${JVM_MAXIMUM_MEMORY:-"{{ confluence_jvm_maximum_memory }}"} -XX:+UseG1GC ${CATALINA_OPTS}"
 CATALINA_OPTS="-Dsynchrony.enable.xhr.fallback=true ${CATALINA_OPTS}"
 CATALINA_OPTS="-Dorg.apache.tomcat.websocket.DEFAULT_BUFFER_SIZE=32768 ${CATALINA_OPTS}"
 CATALINA_OPTS="${START_CONFLUENCE_JAVA_OPTS} ${CATALINA_OPTS}"
-CATALINA_OPTS="-Dconfluence.context.path=${CONFLUENCE_CONTEXT_PATH} ${CATALINA_OPTS}"
-CATALINA_OPTS="-Dconfluence.home={{ confluence_home }} ${CATALINA_OPTS}"
+CATALINA_OPTS="-Dconfluence.home=${CONFLUENCE_HOME:-/var/atlassian/application-data/confluence} ${CATALINA_OPTS}"
+CATALINA_OPTS="-Dcatalina.connector.proxyName=${CATALINA_CONNECTOR_PROXYNAME:-"{{ confluence_catalina_connector_proxyname }}"} ${CATALINA_OPTS}"
+CATALINA_OPTS="-Dcatalina.connector.proxyPort=${CATALINA_CONNECTOR_PROXYPORT:-"{{ confluence_catalina_connector_proxyport }}"} ${CATALINA_OPTS}"
+CATALINA_OPTS="-Dcatalina.connector.scheme=${CATALINA_CONNECTOR_SCHEME:-"{{ confluence_catalina_connector_scheme }}"} ${CATALINA_OPTS}"
+CATALINA_OPTS="-Dcatalina.connector.secure=${CATALINA_CONNECTOR_SECURE:-"{{ confluence_catalina_connector_secure }}"} ${CATALINA_OPTS}"
+CATALINA_OPTS="-Dcatalina.context.path=${CATALINA_CONTEXT_PATH:-} ${CATALINA_OPTS}"
+CATALINA_OPTS="-XX:ReservedCodeCacheSize=256m -XX:+UseCodeCacheFlushing ${CATALINA_OPTS}"
+
 
 export CATALINA_OPTS
+
+sed -i "s/\(<session-timeout>\).*\(<\/session-timeout>\)/\1${SESSION_TIMEOUT:-"{{ confluence_session_timeout }}"}\2/g" ${CONFLUENCE_CATALINA}/confluence/WEB-INF/web.xml
